# Generated by Django 3.1.3 on 2020-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('id_client', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_place', models.CharField(max_length=200)),
                ('total_num_available_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_reduction', models.FloatField()),
                ('reduction_junior', models.FloatField()),
                ('reduction_senior', models.FloatField()),
                ('reduction_card_type', models.CharField(choices=[('NC', 'no reduction'), ('JC', 'junior reduction'), ('SC', 'senior reduction')], default='NC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ticket', models.FloatField()),
                ('place_number', models.IntegerField()),
                ('id_reservation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ride', models.CharField(max_length=200)),
                ('price_ride', models.FloatField()),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_station', models.CharField(max_length=200)),
                ('name_station', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_available_places', models.IntegerField()),
                ('number_reserved_places', models.IntegerField()),
                ('voiture_number', models.IntegerField()),
                ('id_voiture', models.CharField(max_length=200)),
            ],
        ),
    ]
