# Generated by Django 3.1.2 on 2020-11-25 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_available_places_car', models.IntegerField(default=0)),
                ('total_places', models.IntegerField(default=50)),
                ('car_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('card', models.CharField(choices=[('NC', 'no reduction'), ('JC', 'junior reduction'), ('SC', 'senior reduction')], default='NC', max_length=2, primary_key=True, serialize=False)),
                ('percentage', models.FloatField(choices=[(0, '0%'), (0.3, '30%'), (0.2, '20%')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name_station', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=35.0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('departure_time', models.TimeField(default=datetime.time)),
                ('arrival_time', models.TimeField(default=datetime.time)),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_station', to='agency.station')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_station', to='agency.station')),
                ('id_train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.train')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.FloatField()),
                ('place_situation', models.CharField(max_length=200)),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.carride')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.reduction'),
        ),
        migrations.AddField(
            model_name='carride',
            name='id_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.ride'),
        ),
        migrations.AlterUniqueTogether(
            name='carride',
            unique_together={('id_ride', 'car_number')},
        ),
    ]
