# Generated by Django 3.1.3 on 2020-11-12 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_available_places_car', models.IntegerField()),
                ('number_reserved_places_car', models.IntegerField()),
                ('car_number', models.IntegerField()),
                ('id_car', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='total_num_available_places',
            new_name='number_available_places_train',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='no_reduction',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='reduction_junior',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='reduction_senior',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='depart_time',
        ),
        migrations.AddField(
            model_name='client',
            name='reduction_card_type',
            field=models.CharField(choices=[('NC', 'no reduction'), ('JC', 'junior reduction'), ('SC', 'senior reduction')], default='NC', max_length=2),
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='id_place',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_reservation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='id_ride',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='id_station',
            field=models.IntegerField(),
        ),
    ]
