# Generated by Django 3.1.2 on 2020-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='place_situation',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
