# Generated by Django 3.1.3 on 2020-11-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20201112_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='prenom',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='arrival',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='departure',
            new_name='departure_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_number',
        ),
        migrations.AddField(
            model_name='car',
            name='id_train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.train'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='id_ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.ride'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reduction',
            name='reduction_percentage',
            field=models.FloatField(choices=[(0, '0%'), (0.3, '30%'), (0.2, '20%')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.ride'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='agency.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='agency.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='id_train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.train'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='id_train',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='id_car',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='reduction_card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.reduction'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='id_ride',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='id_station',
            field=models.IntegerField(blank=True),
        ),
    ]
