# Generated by Django 3.1.3 on 2020-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20201116_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='station',
            name='id_station',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='id_car',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_reservation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='id_ride',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='train',
            name='id_train',
            field=models.IntegerField(),
        ),
    ]
