# Generated by Django 3.1.3 on 2020-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20201116_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_date',
            field=models.DateField(default='2020-12-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_date',
            field=models.DateField(default='2020-12-25'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='reduction_card_type',
            field=models.CharField(choices=[('NC', 'no reduction'), ('JC', 'junior reduction'), ('SC', 'senior reduction')], default='NC', max_length=2),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
