# Generated by Django 3.1.3 on 2020-11-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20201120_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_station',
            field=models.ForeignKey(db_column='gare_arrivee', on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='agency.station'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_station',
            field=models.ForeignKey(db_column='gare_depart', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='agency.station'),
        ),
    ]
