# Generated by Django 3.1.3 on 2020-11-22 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20201121_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='id_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_available_places_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_reserved_places_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='id_place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='number_available_places_train',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_ticket',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_station',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_station',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price_ride',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='train',
            name='id_train',
            field=models.IntegerField(default=0),
        ),
    ]
